# Generated by Django 4.2 on 2025-02-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_updated_at_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_breaking_news',
            field=models.BooleanField(default=False),
        ),
    ]
